# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VibrationControlDialog
                                 A QGIS plugin
 Blaster Vibration Control
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-02-19
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Bruno S. Mosso
        email                : engbrunomosso@outlook.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'vibration_control_dialog_base.ui'))


class VibrationControlDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(VibrationControlDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        #self.textHelp.setHtml('<div align="center"><img src=":/plugins/vibration_control/DistanciaMinimaCargaMaxima.png" width="400"></div>')
        #<img src=":/plugins/vibration_control/DistanciaMinimaCargaMaxima.png" style="width: 100%; height: auto; border: 1px solid #ccc; border-radius: 8px; padding: 5px;">
        conteudo_atual = self.textHelp.toHtml()
        # Adiciona a imagem ao final do conteúdo existente
        html_com_imagem = conteudo_atual + """
            <div style="text-align: center; margin-top: 15px;">
                <img src=":/plugins/vibration_control/DistanciaMinimaCargaMaxima.png" width="550";">
                <div style="font-size: 12px; color: #555; margin-top: 5px;">
                    Figura: Determinação da distância mínima.
                </div>
            </div>
        """
        

        self.textHelp.setHtml(html_com_imagem)

       

